### PR TITLE
Issue #12: White Label page added

### PR DESCRIPTION
**Pull request by adamrneary**
@fcjne this is fantastic. The only thing I am missing...with the current version of branded_scrn.jpg the fact that it's "Connected Bookkeepers" rather than Profitably is a bit lost. Maybe to fix that:
- We could make the image slightly larger (nothing too extreme, but a big larger
- We could move the macbook pro image into the center with the iPad version on the right. All three (MBP, iPad, and iPhone) versions could have the red header with the Connected Bookkeeper logo showing (same proportions, but all three red).

This would probably be enough to get the message across, I would think! The rest I can take care of on this end...

### CODE REVIEW

**Comment by adamrneary** [comment]
@fcjne i wonder how it would look if we kept the blue well featured on index.html for advisor.html. If the blue gradient "banner" was there and our heading was white lettering, and if the MBP/iPad/iPhone images had a transparent background...

It might look really cool if the image were scooted up a little and the bottom of the MBP (the baseline of the image itself) was in the white area but most of the image was in the blue. That might make the border between the blue banner area and the white below seem like a horizon line. Do you know what I mean?

If we tried that and the image was a bit bigger (per my comments above) but snuck up a bit, it's possible the "As seen on" with logos would appear without scrolling on most screens...

I don't know--what do you think?

**Comment by fcjne** [comment]
Yes, I think it's cool idea to add blue well banner from index.html. 

Regarding MBP/iPad/iPhone image: Let's try this, need to see how it's look live. I'm going to push updates in a few hours.

**Comment by fcjne** [comment]
A,
Please check new version of the header. I've moved "Learn more" button to the bottom of the blue banner, since on the top of the image it takes too much vertical space and looks like image is out of the design flow.

**Comment by adamrneary** [comment]
Fantastic. I love it. Made a couple minor changes on my end, but I will merge tomorrow, and thanks.

Next up is Issue #3. Ultimately, I think I will apply your original work (2 options landing page) to index.html and take the existing index.html and rename it dashboards.html. I could use your help, though, with a version of the MBP/iPad/iPhone just like you have it for the advisor page but with the normal Profitably headers. That's a great image to use for the main page I think. Would you mind making me a copy with the Profitably headers?

Thanks! 

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by fcjne** [comment]
Ok, you want to place MBP image on dashboards.html instead of current artwork? 

And also, just for clarify, all things of issue #3 now actual for dashboards.html?

**Comment by adamrneary** [comment]
I've been pushing a ton of commits up that take care of most of the functionality for issue #3. You're correct that it's for dashboards.html at this point. Right now, a different version of that image is just about the only piece we're missing, and we're going to be ready to push this out!

-A 

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by adamrneary** [comment]
I am going to merge the branch into master, actually. Once you've got an updated copy of the image, you could even email it to me, and I will get it synced in with S3 and everything. We haven't made that process very smooth yet!

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Comment by fcjne** [comment]
I'll mail image to you in a 30 min )

On Fri, May 4, 2012 at 11:41 PM, Adam Neary <
reply@reply.github.com

**Comment by adamrneary** [comment]
Cool. Also, let me know what you think of the site! We've pared it down quite a bit, but it's cohesive for now.

Beyond that image, I've assigned you issue 11 on the same project, and then there's still plenty to do back on the core product when you get a chance (https://github.com/profitably/profitably/issues/assigned/fcjne?state=open).

Appreciate the work to date!
-A

Adam Neary | CEO
adam.neary@profitably.com (mailto:adam.neary@profitably.com)
http://www.profitably.com (http://www.profitably.com/)

**Pull request merged**
